version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

image: &image
  docker:
    - image: cimg/node:18.18.2
  resource_class: medium+

setup: &setup
  - run:
      name: Setup
      command: |
        sudo npm install -g pnpm
        pnpm install

jobs:
  test:
    <<: *image
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run: node --version
      - <<: *setup
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: pnpm test
  build:
    <<: *image
    environment:
      PUBLIC_PROJECT_PATH: microstore
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - <<: *setup
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: pnpm build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: "s3://$S3_ASSETS_BUCKET/team/fe-static-apps/$PUBLIC_PROJECT_PATH/<<pipeline.git.tag>>"

workflows:
  version: 2

  run-tests:
    jobs:
      - test:
          context: commercelayer
          filters:
            tags:
              ignore: /v.*/

  test-build-and-push:
    jobs:
      - test:
          context: commercelayer
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - test
          context: commercelayer
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
            branches:
              ignore: /.*/
